### ISSUE TITLE
navigator.sendBeacon() unavailable when beacon.enabled === false

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot-metrics#25]
[When the `beacon.enabled` pref is `false`, `navigator.sendBeacon()` does not exist.](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/Navigator.webidl#351) So, it might be a good idea to wrap it in a try/catch and just make `sendEvent` a no-op in that case.

Not sure what sets this pref to false, but I suspect some privacy-centric add-on may have done so in my case. As a follow up question - do we want to use some other GA ping mechanism in this case? Warn the user somehow that their input isn't being submitted to Test Pilot? Just quietly honor the pref?

**Comment by jaredhirsch** [comment]
:+1: thanks for filing. looks like the `fetch` API [cannot be disabled by a pref](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/Fetch.webidl), so I'll use that as a fallback.
