### ISSUE TITLE
Make "event" and "object" required only for GA?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot-metrics#6]
The `sendEvent` call requires `event` & `object` properties in the event data. But, the Telemetry ping accepts whatever data we set up in our redshift schema. It seems like those properties are only required by Google Analytics. 

Since we have the transform function for the GA path now, maybe only enforce those property requirements *after* the transform and only if GA is enabled?

**Comment by lmorchard** [comment]
Or, actually, enforce `ea` and `ec` as required in the eventual GA ping, since that's where things end up after a user-supplied transform and [those two are actually required](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#commonhits)

**Comment by jaredhirsch** [comment]
Thanks for filing this bug. The [event telemetry draft](https://docs.google.com/document/d/1hNuS9lUJMvMqgntZXbFA6xZBU9zBpQgo7x73-sXKRpI/edit#heading=h.7hd61k7kegq3) says that event and object (er, method and object...) are required, but I don't know what the final decision was.

We do actually set a default category of 'interactions' already for GA. We could similarly set a default 'object' for Telemetry.

Let me follow up with the data people and see what the guidance is for future experiments.

**Comment by lmorchard** [comment]
Yeah, I think that spec is old. We're not doing the batched submission stuff anymore. 

The latest example I'm going from is how our Tracking Protection experiment is currently handling Telemetry between [`metrics.md`](https://github.com/mozilla/blok/blob/master/docs/metrics.md#client-side) and [`background.js`](https://github.com/mozilla/blok/blob/master/src/js/background.js#L222). That's a running experiment, so I assumed it's a good practical example

**Comment by jaredhirsch** [comment]
Apparently that doc is all that exists. Talking with sunah now but apparently the standard is an array of client timestamp, category, method, object, but not sure what the order is.

**Comment by lmorchard** [comment]
That said, I also don't actually know what the dashboards & pipeline look like for Tracking Protection. But, we do have bugs open for [a re:dash dashboard](https://bugzilla.mozilla.org/show_bug.cgi?id=1333853) and [making data available](https://bugzilla.mozilla.org/show_bug.cgi?id=1333852).

**Comment by lmorchard** [comment]
Maybe @clouserw has more up-to-date info on how this stuff is working now?

**Comment by jaredhirsch** [comment]
ok, so I think I'm just going to add another transform for the client and make event the only required field.

apparently [this](https://docs.google.com/document/d/1hNuS9lUJMvMqgntZXbFA6xZBU9zBpQgo7x73-sXKRpI/edit#heading=h.62xjq5nppfns) is the canonical serialization format: 

```js
[ <integer> clientTimestamp, 
<string> category, 
<string> method, 
<string> object, 
<string | null> value, // apparently an 'extra' string field
<object | null> dict // apparently an 'extra' object with string keys and string values
 ]```

**Comment by jaredhirsch** [comment]
it also turns out that the google doc is the only documentation of the new telemetry format. it's not in any public document. going to follow up with the telemetry team to encourage them to publish the finalized decisions and resolve the many open comments in that gdoc

**Comment by jaredhirsch** [comment]
derp, reversing course again: I'll make all arguments inside the `sendEvent` parameter object optional, so addons can just send _whatever_ keys to Telemetry, and then allow for a transform to reshape things into GA-compatible format. And I guess this library will be jumping up to version 2.0 when that lands.

**Comment by jaredhirsch** [comment]
Hmm. `sendEvent` making keys optional won't technically be a backwards-incompatible change, so I'll plan to bump the version to 1.1.
